version: "3.8"

services:
  date-annotator:
    image: nlpsandbox/date-annotator-example:edge
    container_name: date-annotator
    restart: always
    ports:
      - 9000:8080

  person-name-annotator:
    image: nlpsandbox/person-name-annotator-example:edge
    container_name: person-name-annotator
    restart: always
    ports:
      - 9001:8080

  physical-address-annotator:
    image: nlpsandbox/physical-address-annotator-example:edge
    container_name: physical-address-annotator
    restart: always
    ports:
      - 9002:8080

  phi-deidentifier:
    image: nlpsandbox/phi-deidentifier:edge
    build:
      context: server
      dockerfile: Dockerfile
    container_name: phi-deidentifier
    restart: always
    ports:
      - 9003:8080
    depends_on:
      - date-annotator
      - person-name-annotator
      - physical-address-annotator

  phi-deidentifier-app:
    image: nlpsandbox/phi-deidentifier-app:edge
    build:
      context: client
      dockerfile: Dockerfile
    container_name: phi-deidentifier-app
    restart: always
    ports:
      - 8080:80
    depends_on:
      - phi-deidentifier